CREATE TABLE IF NOT EXISTS t_user
(
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(160) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password VARCHAR(160) NOT NULL ,
    avatar VARCHAR(160) NOT NULL ,
    role int NOT NULL

);